### ISSUE TITLE
执行 docker-compose up 报错

### ISSUE THREAD

**Issue by tanharoh** [vfreex/docker-cowrie#1]
WARNING: Please be aware that .yml is the expected extension in most cases, and using .yaml can cause compatibility issues in future.

ERROR: In file './docker-compose.yaml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.

**Comment by tanharoh** [comment]
升级docker-compose

**Comment by vfreex** [comment]
I will add a note on this issue to README.md.
